handle no connection for calling retrofit request for home fragment
MohabElziny/Ebuy pull request #104
Opened 2022-06-25 19:48 UTC by AhmedAbdallah125

2022-06-25 20:10 UTC, AbdulrahmanAli19 approved these changes

2022-06-26 10:53 UTC, MohabElziny requested changes

2022-06-26 10:53 UTC, MohabElziny commented on app/src/main/java/com/iti/android/team1/ebuy/ui/home/view/HomeFragment.kt
> +import android.util.Log
remove Log

2022-06-26 10:53 UTC, MohabElziny commented on app/src/main/java/com/iti/android/team1/ebuy/NoInternetFragment.kt
> +    }
What is the purpose of this fragment?

2022-06-26 11:01 UTC, AhmedAbdallah125 commented on app/src/main/java/com/iti/android/team1/ebuy/ui/home/view/HomeFragment.kt
> +import android.util.Log
Done

2022-06-26 11:01 UTC, AhmedAbdallah125 commented on app/src/main/java/com/iti/android/team1/ebuy/NoInternetFragment.kt
> +    }
Removed is done

2022-06-26 22:00 UTC, MohabElziny approved these changes

2022-06-26 22:06 UTC, merged